### ISSUE TITLE
Fails with Qt 5.11.1

### ISSUE THREAD

**Issue by probonopd** [TheFutureShell/QtUpdateBridges#3] opened 2019-06-09 23:54 UTC
This program uses Qt version 5.11.1.

```
#!/usr/bin/env bash

# Get Scribus from upstream
wget -c https://gitlab.com/scribus/scribus/-/jobs/227157068/artifacts/raw/Scribus-2f0ab15-x86_64.AppImage

# Make it executable
chmod +x Scribus-*-x86_64.AppImage

# Extract contents of AppImage
./Scribus-*-x86_64.AppImage --appimage-extract

# Configure
cat > updatedeployqt.json <<EOF
{
   // Always use AppImageUpdater for AppImages
   "bridge" : "AppImageUpdater",

   // Use this to comply with GDPR 
   "manual-update-check" : {
       
       // The QObject name where 'Check for Update' has to integrated
       "qmenu-name" : "Help" ,

       // Overrides any QAction with the given substring as text in the given QMenu
       "qaction-to-override" : "Check for"
   }
}
EOF

# Get and run updatedeployqt
wget -O updatedeployqt-x86_64.AppImage "https://git.io/fj4CH"
chmod +x ./updatedeployqt-x86_64.AppImage

# Deploy updater
./updatedeployqt-x86_64.AppImage  squashfs-root/

# Recreate AppImage
wget -c "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage"
chmod +x ./appimagetool-x86_64.AppImage
ARCH=x86_64 ./appimagetool-x86_64.AppImage squashfs-root/ --no-appstream \
         -u $(./Scribus-*-x86_64.AppImage --appimage-updateinfo)
```

results in

```
me@host:~$ ./updatedeployqt-x86_64.AppImage  squashfs-root/
updatedeployqt git-commit d9c76ed, built on Thu Jun  6 18:35:12 2019
Copyright (C) 2019 The Future Shell Laboratory.
Qt plugin injector git-commit 355c81a.
Qt update bridges git-commit e7acd07.

[ 01:53:43 ]     INFO  : will be deploying AppImageUpdater bridge.
[ 01:53:43 ]     INFO  : adding manual update check initialization for this application.
[ 01:53:43 ]     INFO  : QMenu object name(helpCheckUpdates) is given, 'Check for Update' option will be appended.
[ 01:53:43 ]     INFO  : QAction to override is given , QAction with text containing (null) will be overrided.
[ 01:53:43 ]     INFO  : system library path: /lib/x86_64-linux-gnu.
[ 01:53:43 ]     INFO  : deploy library path: squashfs-root/usr/lib.
[ 01:53:43 ]     INFO  : deploy plugins path: squashfs-root/usr/plugins.
[ 01:53:43 ]     INFO  : QXcb plugin path: squashfs-root/usr/plugins/platforms/libqxcb.so.
[ 01:53:43 ]     INFO  : copying required bridge..
[ 01:53:43 ]     INFO  : successfully copied AppImageUpdater bridge to deploy directory.
[ 01:53:45 ]     INFO  : deployed bridge successfully!.
[ 01:53:49 ]     INFO  : qt version tag: qt_version_tag_5_1.
[ 01:53:49 ]    FATAL  : only qt version 5.6.0 and above are supported.
[ 01:53:49 ]    FATAL  : cannot determine qt version to target.
[ 01:53:49 ]    FATAL  : qt plugin injection failed.
[ 01:53:49 ]    FATAL  : deploy failed , exiting with errors.
```

**Comment by probonopd** [comment] 2019-06-09 23:59
```
me@host:~$ strings squashfs-root/usr/lib/libQt5Core.so.5 | grep qt_version_tag
qt_version_tag_5_11
qt_version_tag
qt_version_tag_5_10
qt_version_tag_5_8
qt_version_tag_5_9
qt_version_tag_5_7
qt_version_tag_5_6
qt_version_tag_5_4
qt_version_tag_5_5
qt_version_tag_5_3
qt_version_tag_5_2
qt_version_tag_5_0
qt_version_tag_5_1
```

**Comment by probonopd** [comment] 2019-06-10 14:17
When I specify the Qt version manually,

```
# Configure
cat > updatedeployqt.json <<EOF
{
   "qt-version" : "5.11.1",

   // Always use AppImageUpdater for AppImages
   "bridge" : "AppImageUpdater",

   // Use this to comply with GDPR 
   "manual-update-check" : {
       
       // The QObject name where 'Check for Update' has to integrated
       "qmenu-name" : "helpCheckUpdates" ,

       // Overrides any QAction with the given substring as text in the given QMenu
       "qaction-to-override" : "Check for Updates"
   }
}
EOF
```
then it says 

```
[ 16:16:31 ]     INFO  : deployed bridge successfully!.
[ 16:16:31 ]     INFO  : copying modified qxcb plugin for qt version 5.10.0.
[ 16:16:31 ]     INFO  : successfully copied qxcb plugin.
[ 16:16:31 ]     INFO  : qt plugin injections was successful.
```

Note that `5.10.0` is wrong, I have specified `5.11.1`.

**Comment by antony-jr** [comment] 2019-06-10 16:03
Sorry for the late response, I'm currently out of station. Its a bug. It just fails to detect the correct qt version. We just need to use version 5.10.0 for Qt version greater than or equal to 5.10.0.

**Comment by probonopd** [comment] 2019-06-10 16:08
Did you see

> And it does __not__ seem to work; the menu is not overridden.

What am I doing wrong then? Should I manually set `"qt-version" : "5.10.0",` for now?

**Comment by antony-jr** [comment] 2019-06-10 16:12
> Did you see
>> And it does not seem to work; the menu is not overridden.

I think its not your fault. It simply can't find the QAction. I will fix this as soon as I get home.

**Comment by antony-jr** [comment] 2019-06-12 10:25
The problem is that you used the QMenu's title and not the **QObject name** but now we check both the title and QObject name so its now fixed. The previous version could not find the qt version correctly because it read only the last qt version tag which was 5.1 which is indeed unsupported but in the latest release this was fixed by choosing the highest qt version tag from all found qt version tags, So the version error was also fixed.

**Closed by antony-jr** 2019-06-12 10:25 UTC

**Comment by probonopd** [comment] 2019-06-12 19:30
> now we check both the title and QObject name

Awesome! Question: What happens if the user has a different language? Will it still work if we specify the English title?

**Comment by antony-jr** [comment] 2019-06-12 19:32
> Awesome! +1 Question: What happens if the user has a different language? Will it still work if we specify the English title?

I don't know but I think it won't work so you have to use the QObject name. For now I only rely on UTF-8 so any language that fits in it should work well.

**Comment by probonopd** [comment] 2019-06-12 19:38
> I don't know but I think it won't work so you have to use the QObject name.

Then we should not offer the other option at all since it will mean it would not work for non-English users...

**Comment by antony-jr** [comment] 2019-06-12 19:39
> Then we should not offer the other option at all since it will mean it would not work for non-English users...

But I think its crucial, We can make it work under any language if we put some effort.

**Comment by probonopd** [comment] 2019-06-12 19:41
Yes, either have it work in all languages or remove it.
